server:
  port: 6868 #注册中心端口

spring:
  application:
    name: microservice-eureka

eureka:
  client:
    register-with-eureka: true  #是否将自己注册到Eureka服务中，本身就是所有无需注册,eureka高可用下需要注册自己
    fetch-registry: true   #是否从Eureka上获取注册信息
    service-url:    #Eureka客户端与Eureka服务端进行交互的地址,高可用中自己是客户端
      defaultZone: http://whling:whling123@127.0.0.1:6868/eureka/

security:
  basic:
    enabled: true   #开启基于http basic的认证
  user:
    name: whling
    password: whling123


