server:
  port: 8082

microservice:
  item:
    address: http://localhost:8081/item/

spring:
  application:
    name: microservice-order #指定服务名

eureka:
  client:
    registerWithEureka: false #是否将自己注册到Eureka服务中，默认为true
    fetchRegistry: true #是否从Eureka中获取注册信息，默认为true
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址
      defaultZone: http://whling:whling123@127.0.0.1:6868/eureka/,http://whling:whling123@127.0.0.1:6869/eureka/